---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(janitor)
library(tidyverse)
library(lubridate)
library(rvest)
library(stringr)
library(tidycensus)
```


```{r}
eligibility <- read_csv("../data/eligibility/eligibility_age_by_state.csv", show_col_types = FALSE) |>
  clean_names() 

pop <- get_estimates(
  geography = "state",
  product   = "characteristics",
  breakdown = c("AGE"),
  breakdown_labels = TRUE,
  vintage   = 2024,            
  year      = 2024
) |>
  filter(AGE != "All ages") |>
  mutate(age = as.integer(AGE)) |>
  select(state = NAME, age, pop = value) |>
  group_by(state) |>
  summarise(age_18_plus = sum(pop[age > 17]),
            age_19_plus = sum(pop[age > 18]),
            age_21_plus = sum(pop[age > 20])) |>
  pivot_longer(cols = c(age_18_plus, age_19_plus, age_21_plus), names_to = "age_group", values_to = "population")

eligibile_population_by_state <- eligibility |>
  left_join(pop, join_by(state, minimum_age == age_group)) |>
  rename(eligible_population = population)

write_csv(eligibile_population_by_state, "../data/eligibility/eligible_population_by_state.csv")
```


```{r}
eligible_population_by_state |>
  filter(!is.na(minimum_age)) |>
  arrange(desc(eligible_population)) |>
  group_by(state) |>
  slice_head(n = 1) |>
  ungroup() |>
  summarise(total_eligible_population = sum(eligible_population))

eligible_population_by_state |>
  filter(!is.na(minimum_age)) |>
  group_by(state) |>
  count()

eligible_population_by_state |>
  filter_out(state %in% c("Hawaii", "Idaho", "Mississippi", "Louisiana", "Maryland", "Ohio", "Pennsylvania", "Vermont", "Massachusetts", "Tennessee", "New York")) |>
  filter(!is.na(minimum_age)) |>
  group_by(state) |>
  mutate(state_eligibility = paste(sort(unique(type)), collapse = ", ")) |>
  filter(state_eligibility != "college player props") |>
  group_by(state, minimum_age, eligible_population) |>
  count() |>
  filter(n == 1) |>
  pivot_wider(names_from = minimum_age, values_from = eligible_population) |>
  mutate(otherwise_ineligible_population = case_when(
    is.na(age_19_plus) & is.na(age_18_plus) ~ age_21_plus,
    is.na(age_21_plus) & is.na(age_18_plus) ~ age_19_plus,
    is.na(age_21_plus) & is.na(age_19_plus) ~ age_18_plus,
    !is.na(age_18_plus) & !is.na(age_21_plus) ~ age_18_plus - age_21_plus)) |>
  ungroup() |>
  summarise(total_otherwise_ineligible_population = sum(otherwise_ineligible_population, na.rm = TRUE))


eligible_population_by_state |>
  filter(!is.na(minimum_age)) |>
  group_by(state) |>
  mutate(state_eligibility = paste(sort(unique(type)), collapse = ", ")) |>
  filter(state_eligibility == "prizepicks college player picks") |>
  ungroup() |>
  summarise(otherwise_ineligible_population = sum(eligible_population, na.rm = TRUE))

eligible_population_by_state |>
  filter(state %in% c("Alaska", "Utah", "Oklahoma", "Alabama", "South Carolina", "Minnesota", "Georgia", "Texas", "California")) |>
  filter(!is.na(minimum_age)) |>
  summarise(total_eligible_population = sum(eligible_population, na.rm = TRUE))

(82316744/126991829*100)
```

